# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cmtip_service_pb2 as cmtip__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cmtip_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CmtipBusStub:
    """─── Service Definition ────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/cmtip.CmtipBus/RegisterModel',
                request_serializer=cmtip__service__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=cmtip__service__pb2.RegisterModelResponse.FromString,
                _registered_method=True)
        self.TrainAdapter = channel.unary_unary(
                '/cmtip.CmtipBus/TrainAdapter',
                request_serializer=cmtip__service__pb2.TrainAdapterRequest.SerializeToString,
                response_deserializer=cmtip__service__pb2.TrainAdapterResponse.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/cmtip.CmtipBus/GetConversation',
                request_serializer=cmtip__service__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=cmtip__service__pb2.GetConversationResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/cmtip.CmtipBus/GetStatus',
                request_serializer=cmtip__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=cmtip__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SendText = channel.unary_unary(
                '/cmtip.CmtipBus/SendText',
                request_serializer=cmtip__service__pb2.SendTextRequest.SerializeToString,
                response_deserializer=cmtip__service__pb2.SendTextResponse.FromString,
                _registered_method=True)
        self.SendTensor = channel.unary_unary(
                '/cmtip.CmtipBus/SendTensor',
                request_serializer=cmtip__service__pb2.SendTensorRequest.SerializeToString,
                response_deserializer=cmtip__service__pb2.SendTensorResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.stream_stream(
                '/cmtip.CmtipBus/Subscribe',
                request_serializer=cmtip__service__pb2.TensorPacket.SerializeToString,
                response_deserializer=cmtip__service__pb2.TensorPacket.FromString,
                _registered_method=True)


class CmtipBusServicer:
    """─── Service Definition ────────────────────────────────────────────────────

    """

    def RegisterModel(self, request, context):
        """Control plane
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainAdapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendText(self, request, context):
        """Data plane
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request_iterator, context):
        """Bidirectional streaming conversation
        Two models can connect and exchange tensor packets in real time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CmtipBusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=cmtip__service__pb2.RegisterModelRequest.FromString,
                    response_serializer=cmtip__service__pb2.RegisterModelResponse.SerializeToString,
            ),
            'TrainAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainAdapter,
                    request_deserializer=cmtip__service__pb2.TrainAdapterRequest.FromString,
                    response_serializer=cmtip__service__pb2.TrainAdapterResponse.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=cmtip__service__pb2.GetConversationRequest.FromString,
                    response_serializer=cmtip__service__pb2.GetConversationResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=cmtip__service__pb2.StatusRequest.FromString,
                    response_serializer=cmtip__service__pb2.StatusResponse.SerializeToString,
            ),
            'SendText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendText,
                    request_deserializer=cmtip__service__pb2.SendTextRequest.FromString,
                    response_serializer=cmtip__service__pb2.SendTextResponse.SerializeToString,
            ),
            'SendTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTensor,
                    request_deserializer=cmtip__service__pb2.SendTensorRequest.FromString,
                    response_serializer=cmtip__service__pb2.SendTensorResponse.SerializeToString,
            ),
            'Subscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=cmtip__service__pb2.TensorPacket.FromString,
                    response_serializer=cmtip__service__pb2.TensorPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cmtip.CmtipBus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cmtip.CmtipBus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CmtipBus:
    """─── Service Definition ────────────────────────────────────────────────────

    """

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmtip.CmtipBus/RegisterModel',
            cmtip__service__pb2.RegisterModelRequest.SerializeToString,
            cmtip__service__pb2.RegisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmtip.CmtipBus/TrainAdapter',
            cmtip__service__pb2.TrainAdapterRequest.SerializeToString,
            cmtip__service__pb2.TrainAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmtip.CmtipBus/GetConversation',
            cmtip__service__pb2.GetConversationRequest.SerializeToString,
            cmtip__service__pb2.GetConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmtip.CmtipBus/GetStatus',
            cmtip__service__pb2.StatusRequest.SerializeToString,
            cmtip__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmtip.CmtipBus/SendText',
            cmtip__service__pb2.SendTextRequest.SerializeToString,
            cmtip__service__pb2.SendTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cmtip.CmtipBus/SendTensor',
            cmtip__service__pb2.SendTensorRequest.SerializeToString,
            cmtip__service__pb2.SendTensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cmtip.CmtipBus/Subscribe',
            cmtip__service__pb2.TensorPacket.SerializeToString,
            cmtip__service__pb2.TensorPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
